version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      

      
      - run:
          command: npm run test:chrome
          
      - store_artifacts:
          path: test-results/testcafe
          
          
      - run:
          command: npm run html:report
          
      - store_artifacts:
           path: test-results/testcafe
        

